Change app to QR scanner
spbu-math-cs-mse/loyalty-sys pull request #13
Opened 2024-11-12 17:27 UTC by ArtyomPeshkov

2024-11-13 10:04 UTC, mmmmarryyy requested changes

2024-11-13 10:04 UTC, mmmmarryyy commented on UserApp/app/src/main/res/layout/activity_main.xml
> +        android:text="Scan Customer Data"/>
относительно android:text, строки обычно выносят в strings.xml и оттуда подтягивают (пример можно найти [тут](https://habr.com/ru/articles/133503/))

2024-11-13 10:10 UTC, ArtyomPeshkov commented on UserApp/app/src/main/java/com/loyalitysys/MainActivity.kt
> +    private lateinit var tvPurchaseData: TextView
Да, от textView, поменяю

2024-11-13 10:10 UTC, ArtyomPeshkov commented on UserApp/app/src/main/java/com/loyalitysys/MainActivity.kt
> +        val btnSendData = findViewById<Button>(R.id.btnSendData)
Аналогично

2024-11-13 10:10 UTC, ArtyomPeshkov commented on UserApp/app/src/main/java/com/loyalitysys/MainActivity.kt
> +                    if (currentType == "customer") {
Ок

2024-11-13 10:12 UTC, ArtyomPeshkov commented on UserApp/app/src/main/java/com/loyalitysys/MainActivity.kt
> +                        tvCustomerData.text = "Customer Data: Scanned"
Окей, пока сделаем что-то типа enum-а, но в перспективе там может понадобиться что-то другое

2024-11-13 10:12 UTC, ArtyomPeshkov commented on UserApp/app/src/main/java/com/loyalitysys/network/NetworkHandler.kt
> +object NetworkSetting {
Опечатка

2024-11-13 10:14 UTC, ArtyomPeshkov commented on UserApp/app/src/main/java/com/loyalitysys/network/NetworkHandler.kt
> +data class PurchaseRequest(val user_id: String, val products: List<Product>)
Аналогично

2024-11-13 10:14 UTC, ArtyomPeshkov commented on UserApp/app/src/main/java/com/loyalitysys/network/NetworkHandler.kt
> +    fun sendLastPurchase(user_id: String, products: List<Product> = listOf(Product("T-shirt", (1).toString()))) {
Тут наверное стоит поменять

2024-11-13 10:16 UTC, ArtyomPeshkov commented on UserApp/app/src/main/res/layout/activity_main.xml
> +        android:text="Scan Customer Data"/>
Поправлю

2024-11-13 10:27 UTC, mmmmarryyy commented on UserApp/app/src/main/java/com/loyalitysys/network/NetworkHandler.kt
> +data class Product(val product_id: String, val quantity: String)
Поняла, вопрос нет. Тогда можешь, пожалуйста, пометку об этом оставить?

2024-11-13 10:29 UTC, ArtyomPeshkov commented on UserApp/app/src/main/java/com/loyalitysys/network/NetworkHandler.kt
> +data class Product(val product_id: String, val quantity: String)
Ага, хорошо

2024-11-13 12:48 UTC, mmmmarryyy commented on UserApp/app/src/main/AndroidManifest.xml
>  <manifest xmlns:android="http://schemas.android.com/apk/res/android"
нюанс не по этому файлу, а в общем, в codestyle договорились папки через _ называть. Есть возможность корневую папку UserApp так переименовать?

2024-11-17 15:10 UTC, mmmmarryyy requested changes

2024-11-17 15:10 UTC, mmmmarryyy commented on user_app/app/src/main/java/com/loyalitysys/MainActivity.kt
> +}
LF

2024-11-17 15:10 UTC, mmmmarryyy commented on user_app/app/src/main/res/values/strings.xml
> +</resources>
LF?

2024-11-17 15:10 UTC, mmmmarryyy commented on user_app/app/src/main/res/values/themes.xml
> +</resources>
LF?

2024-11-17 15:10 UTC, mmmmarryyy commented on web-app/package-lock.json
> -        "vue-router": "^4.0.3"
кажется, задело web_app случайно, поправь, пожалуйста

2024-11-17 15:10 UTC, mmmmarryyy commented on user_app/app/src/main/res/values/strings.xml
> +</resources>
а так по строкам кул!

2024-11-18 12:37 UTC, mmmmarryyy requested changes

2024-11-18 12:37 UTC, mmmmarryyy commented on web-app/package-lock.json
> +}
LF)

2024-11-18 12:37 UTC, mmmmarryyy commented on web-app/package.json
> +}
LF

2024-11-20 08:31 UTC, mmmmarryyy approved these changes

2024-11-20 08:31 UTC, merged