web communication
spbu-math-cs-mse/loyalty-sys pull request #16
Opened 2024-11-18 23:29 UTC by WOTiMaruf

2024-11-19 11:21 UTC, mmmmarryyy requested changes

2024-11-19 11:21 UTC, mmmmarryyy commented on web_app/src/components/ChartNumberDisplay.vue
> +    case "rub":
предлагаю вынести этот текст в константы, например, сделать enum, если он есть в vue

2024-11-19 11:21 UTC, mmmmarryyy commented on web_app/src/views/StatsView.vue
> +      axios.get("http://localhost:8080/data/total_purchases", {
а ты не тестил совместимость с бэкендом? кажется, url вроде неправильный, там на другом порту запускается, и, кажется, что мы не хотим общаться по localhost. Поправь url, пожалуйста, и проверь, что взаимодействие с бэкендом корректное по нужным тебе запросам

2024-11-19 11:21 UTC, mmmmarryyy commented on web_app/src/views/StatsView.vue
>            title="Cумма покупок"
А во vue есть возможность здесь не хардкодить строки?

2024-11-19 11:51 UTC, WOTiMaruf commented on web_app/src/components/ChartNumberDisplay.vue
> +    case "rub":
enum-ов нет, getMoneySymbol будет использоваться только в этом компоненте, нигде не потребуется

2024-11-23 19:16 UTC, WOTiMaruf commented on web_app/src/views/StatsView.vue
>            title="Cумма покупок"
нит(

2024-11-23 19:18 UTC, mmmmarryyy approved these changes

2024-11-23 19:18 UTC, merged